version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ~/repo/.circleci/requirements.txt
            #ssh ec2-user@ec2-34-227-109-165.compute-1.amazonaws.com "/bin/bash ./.circleci/circleCD.sh"
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m py_compile ~/repo/FrontEnd/Flask/SkyAudio.py

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-results
